### Assets
GET http://localhost:8888/assets

### Assets DB
GET http://localhost:8888/pg/assets

### Quote
GET http://localhost:8888/quotes/TSLA

### Quote DB
GET http://localhost:8888/pg/quotes/AMZN

### Watchlist
GET http://localhost:8888/account/watchlist/d8f7386a-9b33-4765-98f4-ea2fda341b45

### Watchlist DB
GET http://localhost:8888/pg/account/watchlist/d8f7386a-9b33-4765-98f4-ea2fda341b45

### Watchlist Insert
PUT http://localhost:8888/pg/account/watchlist/100
Content-Type: application/json

{
  "assets": [
    {
      "name": "TSLA"
    },
    {
      "name": "AAPL"
    }
  ]
}
